# 0. Setup Paths

In [6]:
WORKSPACE_PATH = 'Tensorflow/workspace'
SCRIPTS_PATH = 'Tensorflow/scripts'
APIMODEL_PATH = 'Tensorflow/models'
ANNOTATION_PATH = WORKSPACE_PATH+'/annotations'
IMAGE_PATH = WORKSPACE_PATH+'/images'
MODEL_PATH = WORKSPACE_PATH+'/models'
PRETRAINED_MODEL_PATH = WORKSPACE_PATH+'/pre-trained-models'
CONFIG_PATH = MODEL_PATH+'/my_ssd_mobnet/pipeline.config'
CHECKPOINT_PATH = MODEL_PATH+'/my_ssd_mobnet/'

# 1. Create Label Map

In [2]:
labels = [
    {'name':'Hello', 'id':1},
    {'name':'Yes', 'id':2},
    {'name':'No', 'id':3},
    {'name':'Thank You', 'id':4},
    {'name':'I Love You', 'id':5}
]

with open(ANNOTATION_PATH + '/label_map.pbtxt', 'w') as f:
    for label in labels:
        f.write('item { \n')
        f.write('\tname:\'{}\'\n'.format(label['name']))
        f.write('\tid:{}\n'.format(label['id']))
        f.write('}\n')

# 2. Covert xml label to csv

In [3]:
!python {SCRIPTS_PATH + '/generate_csv.py'} {'xml'} {IMAGE_PATH + '/train'} {IMAGE_PATH + '/train/output.csv'}
!python {SCRIPTS_PATH + '/generate_csv.py'} {'xml'} {IMAGE_PATH + '/test'} {IMAGE_PATH + '/test/output.csv'}

100%|█████████████████████████████████████████| 19/19 [00:00<00:00, 1992.44it/s]


# 3. Create TF records

In [4]:
!python {SCRIPTS_PATH + '/generate_tfrecord.py'} {IMAGE_PATH + '/train/output.csv'} {ANNOTATION_PATH + '/label_map.pbtxt'} {IMAGE_PATH + '/train'} {"train.record"}
!python {SCRIPTS_PATH + '/generate_tfrecord.py'} {IMAGE_PATH + '/test/output.csv'} {ANNOTATION_PATH + '/label_map.pbtxt'} {IMAGE_PATH + '/test'} {"test.record"}


groups: 100%|██████████████████████████████████| 53/53 [00:00<00:00, 493.09it/s]
Successfully created the TFRecords: /Users/raginidwivedi/Documents/repos/RealTimeObjectDetection/train.record
groups: 100%|██████████████████████████████████| 19/19 [00:00<00:00, 624.48it/s]
Successfully created the TFRecords: /Users/raginidwivedi/Documents/repos/RealTimeObjectDetection/test.record


# 4. Download TF Models Pretrained Models from Tensorflow Model Zoo

In [5]:
!cd Tensorflow && git clone https://github.com/tensorflow/models

Cloning into 'models'...
remote: Enumerating objects: 33, done.
remote: Counting objects: 100% (33/33), done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 53687 (delta 16), reused 18 (delta 1), pack-reused 53654
Receiving objects: 100% (53687/53687), 569.66 MiB | 12.95 MiB/s, done.
Resolving deltas: 100% (36881/36881), done.


# 5. Copy Model Config to Training Folder

In [3]:
CUSTOM_MODEL_NAME = 'my_ssd_mobnet' 

In [7]:
!mkdir {'Tensorflow/workspace/models/'+CUSTOM_MODEL_NAME}
!cp {PRETRAINED_MODEL_PATH+'/ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8/pipeline.config'} {MODEL_PATH+'/'+CUSTOM_MODEL_NAME}

# 6. Update Config For Transfer Learning

In [4]:
import tensorflow as tf
from object_detection.utils import config_util
from object_detection.protos import pipeline_pb2
from google.protobuf import text_format

In [7]:
CONFIG_PATH = MODEL_PATH+'/'+CUSTOM_MODEL_NAME+'/pipeline.config'

In [8]:
config = config_util.get_configs_from_pipeline_file(CONFIG_PATH)

In [9]:
config

{'model': ssd {
   num_classes: 5
   image_resizer {
     fixed_shape_resizer {
       height: 320
       width: 320
     }
   }
   feature_extractor {
     type: "ssd_mobilenet_v2_fpn_keras"
     depth_multiplier: 1.0
     min_depth: 16
     conv_hyperparams {
       regularizer {
         l2_regularizer {
           weight: 3.9999998989515007e-05
         }
       }
       initializer {
         random_normal_initializer {
           mean: 0.0
           stddev: 0.009999999776482582
         }
       }
       activation: RELU_6
       batch_norm {
         decay: 0.996999979019165
         scale: true
         epsilon: 0.0010000000474974513
       }
     }
     use_depthwise: true
     override_base_feature_extractor_hyperparams: true
     fpn {
       min_level: 3
       max_level: 7
       additional_layer_depth: 128
     }
   }
   box_coder {
     faster_rcnn_box_coder {
       y_scale: 10.0
       x_scale: 10.0
       height_scale: 5.0
       width_scale: 5.0
     }
   }
   match

In [10]:
pipeline_config = pipeline_pb2.TrainEvalPipelineConfig()
with tf.io.gfile.GFile(CONFIG_PATH, "r") as f:                                                                                                                                                                                                                     
    proto_str = f.read()                                                                                                                                                                                                                                          
    text_format.Merge(proto_str, pipeline_config)

In [11]:
pipeline_config.model.ssd.num_classes = 5
pipeline_config.train_config.batch_size = 4
pipeline_config.train_config.fine_tune_checkpoint = PRETRAINED_MODEL_PATH+'/ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8/checkpoint/ckpt-0'
pipeline_config.train_config.fine_tune_checkpoint_type = "detection"
pipeline_config.train_input_reader.label_map_path= ANNOTATION_PATH + '/label_map.pbtxt'
pipeline_config.train_input_reader.tf_record_input_reader.input_path[:] = [ANNOTATION_PATH + '/train.record']
pipeline_config.eval_input_reader[0].label_map_path = ANNOTATION_PATH + '/label_map.pbtxt'
pipeline_config.eval_input_reader[0].tf_record_input_reader.input_path[:] = [ANNOTATION_PATH + '/test.record']

In [12]:
config_text = text_format.MessageToString(pipeline_config)                                                                                                                                                                                                        
with tf.io.gfile.GFile(CONFIG_PATH, "wb") as f:                                                                                                                                                                                                                     
    f.write(config_text)

# 7. Train the model

In [15]:
print("""python {}/research/object_detection/model_main_tf2.py --model_dir={}/{} --pipeline_config_path={}/{}/pipeline.config --num_train_steps=10000""".format(APIMODEL_PATH, MODEL_PATH,CUSTOM_MODEL_NAME,MODEL_PATH,CUSTOM_MODEL_NAME))

python Tensorflow/models/research/object_detection/model_main_tf2.py --model_dir=Tensorflow/workspace/models/my_ssd_mobnet --pipeline_config_path=Tensorflow/workspace/models/my_ssd_mobnet/pipeline.config --num_train_steps=10000


# 8. Load Train Model From Checkpoint

In [13]:
import os
from object_detection.utils import label_map_util
from object_detection.utils import visualization_utils as viz_utils
from object_detection.builders import model_builder

In [14]:
# Load pipeline config and build a detection model
configs = config_util.get_configs_from_pipeline_file(CONFIG_PATH)
detection_model = model_builder.build(model_config=configs['model'], is_training=False)

# Restore checkpoint
ckpt = tf.compat.v2.train.Checkpoint(model=detection_model)
ckpt.restore(os.path.join(CHECKPOINT_PATH, 'ckpt-11')).expect_partial()

@tf.function
def detect_fn(image):
    image, shapes = detection_model.preprocess(image)
    prediction_dict = detection_model.predict(image, shapes)
    detections = detection_model.postprocess(prediction_dict, shapes)
    return detections

# 9. Detect in Real-Time

In [15]:
import cv2 
import numpy as np

In [16]:
category_index = label_map_util.create_category_index_from_labelmap(ANNOTATION_PATH+'/label_map.pbtxt')

In [17]:
#cap.release()

In [18]:
# Setup capture
cap = cv2.VideoCapture(0)
width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

In [ ]:
while True: 
    ret, frame = cap.read()
    image_np = np.array(frame)
    
    input_tensor = tf.convert_to_tensor(np.expand_dims(image_np, 0), dtype=tf.float32)
    detections = detect_fn(input_tensor)
    
    num_detections = int(detections.pop('num_detections'))
    detections = {key: value[0, :num_detections].numpy()
                  for key, value in detections.items()}
    detections['num_detections'] = num_detections

    # detection_classes should be ints.
    detections['detection_classes'] = detections['detection_classes'].astype(np.int64)

    label_id_offset = 1
    image_np_with_detections = image_np.copy()

    viz_utils.visualize_boxes_and_labels_on_image_array(
                image_np_with_detections,
                detections['detection_boxes'],
                detections['detection_classes']+label_id_offset,
                detections['detection_scores'],
                category_index,
                use_normalized_coordinates=True,
                max_boxes_to_draw=5,
                min_score_thresh=.5,
                agnostic_mode=False)

    print(image_np_with_detections)
    print("\n")
    cv2.imshow('object detection',  cv2.resize(image_np_with_detections, (800, 600)))
    
    if cv2.waitKey(1) & 0xFF == ord('q'):
        cap.release()
        break

[[[30 42 54]
  [30 42 54]
  [30 42 54]
  ...
  [48 51 69]
  [48 51 69]
  [47 50 68]]

 [[30 42 54]
  [30 42 54]
  [30 42 54]
  ...
  [48 51 69]
  [48 51 69]
  [47 50 68]]

 [[27 41 53]
  [27 41 53]
  [27 41 53]
  ...
  [47 53 70]
  [47 53 70]
  [46 51 69]]

 ...

 [[43 32 38]
  [44 33 39]
  [45 34 40]
  ...
  [33 30 33]
  [30 27 30]
  [29 26 28]]

 [[42 31 37]
  [43 32 38]
  [44 33 39]
  ...
  [33 28 31]
  [32 26 30]
  [31 25 28]]

 [[42 31 37]
  [43 32 38]
  [43 32 38]
  ...
  [32 26 30]
  [32 26 30]
  [32 26 30]]]


[[[ 28  45  56]
  [ 27  44  55]
  [ 26  43  54]
  ...
  [116 134 160]
  [114 133 159]
  [114 133 159]]

 [[ 28  45  56]
  [ 27  44  55]
  [ 27  44  55]
  ...
  [117 135 162]
  [116 134 160]
  [116 134 160]]

 [[ 30  42  54]
  [ 30  42  54]
  [ 31  43  55]
  ...
  [114 137 163]
  [113 135 163]
  [113 135 163]]

 ...

 [[ 39  24  27]
  [ 39  24  27]
  [ 39  25  25]
  ...
  [161 181 194]
  [161 181 194]
  [163 184 196]]

 [[ 39  24  27]
  [ 39  24  27]
  [ 39  24  27]
  ...


[[[ 36  40  48]
  [ 34  38  46]
  [ 32  36  45]
  ...
  [103 129 152]
  [101 128 151]
  [100 127 150]]

 [[ 37  41  49]
  [ 35  39  47]
  [ 32  36  45]
  ...
  [104 130 153]
  [103 129 152]
  [100 127 150]]

 [[ 39  41  49]
  [ 37  38  47]
  [ 32  36  45]
  ...
  [102 130 153]
  [100 129 152]
  [ 98 127 150]]

 ...

 [[ 25  30  29]
  [ 26  31  30]
  [ 26  31  30]
  ...
  [136 160 176]
  [140 162 179]
  [143 165 182]]

 [[ 27  33  30]
  [ 30  35  32]
  [ 30  35  32]
  ...
  [132 159 175]
  [134 161 175]
  [137 164 178]]

 [[ 30  35  32]
  [ 32  38  35]
  [ 32  38  35]
  ...
  [130 157 173]
  [129 156 170]
  [132 160 173]]]


[[[ 18  35  46]
  [ 19  36  47]
  [ 18  35  46]
  ...
  [103 132 154]
  [102 130 153]
  [100 129 152]]

 [[ 19  36  47]
  [ 20  37  48]
  [ 19  36  47]
  ...
  [103 132 154]
  [102 130 153]
  [100 129 152]]

 [[ 20  38  46]
  [ 21  39  48]
  [ 20  38  46]
  ...
  [100 130 150]
  [100 130 150]
  [100 130 150]]

 ...

 [[ 31  31  33]
  [ 29  28  31]
  [ 28  27  30]
  

[[[ 41  53  60]
  [ 43  54  61]
  [ 43  55  60]
  ...
  [103 139 158]
  [103 139 158]
  [103 139 158]]

 [[ 41  53  60]
  [ 43  54  61]
  [ 44  56  61]
  ...
  [103 139 158]
  [103 139 158]
  [103 139 158]]

 [[ 41  52  62]
  [ 43  53  63]
  [ 44  54  64]
  ...
  [104 141 158]
  [104 141 160]
  [103 139 158]]

 ...

 [[226 129 113]
  [224 127 110]
  [224 125 109]
  ...
  [161 181 191]
  [161 181 191]
  [161 181 191]]

 [[234 128 104]
  [232 127 103]
  [232 124 101]
  ...
  [160 180 190]
  [160 180 190]
  [161 181 191]]

 [[230 124 101]
  [228 122  98]
  [229 120  97]
  ...
  [159 178 189]
  [160 180 190]
  [160 180 190]]]


[[[ 43  51  62]
  [ 45  53  63]
  [ 46  54  64]
  ...
  [109 137 162]
  [109 137 162]
  [109 137 162]]

 [[ 43  51  62]
  [ 45  53  63]
  [ 47  55  65]
  ...
  [109 137 162]
  [107 135 160]
  [107 135 160]]

 [[ 43  51  63]
  [ 45  52  64]
  [ 46  53  65]
  ...
  [109 137 162]
  [107 135 160]
  [106 134 159]]

 ...

 [[233 114  77]
  [233 114  77]
  [236 116  79]
  

[[[ 50  65  74]
  [ 51  67  76]
  [ 53  66  76]
  ...
  [119 161 184]
  [119 161 184]
  [119 161 184]]

 [[ 50  65  74]
  [ 51  67  76]
  [ 53  66  76]
  ...
  [120 162 185]
  [120 162 185]
  [120 162 185]]

 [[ 49  64  73]
  [ 50  65  74]
  [ 51  67  76]
  ...
  [121 164 185]
  [121 164 185]
  [121 164 185]]

 ...

 [[ 84  50  37]
  [ 83  49  36]
  [ 81  46  34]
  ...
  [174 200 203]
  [171 199 202]
  [168 197 199]]

 [[ 94  48  37]
  [ 96  49  38]
  [ 96  49  38]
  ...
  [163 193 197]
  [162 192 196]
  [160 191 195]]

 [[104  57  47]
  [104  57  47]
  [104  57  47]
  ...
  [152 183 187]
  [152 183 187]
  [151 182 186]]]


[[[ 47  60  76]
  [ 47  60  76]
  [ 48  61  77]
  ...
  [114 156 179]
  [115 158 179]
  [116 160 180]]

 [[ 48  61  77]
  [ 48  61  77]
  [ 48  61  77]
  ...
  [114 156 179]
  [115 158 179]
  [116 160 180]]

 [[ 48  61  77]
  [ 48  61  77]
  [ 46  61  77]
  ...
  [121 156 180]
  [122 158 181]
  [124 159 183]]

 ...

 [[ 92  55  45]
  [ 90  52  42]
  [ 90  52  42]
  

[[[ 43  70  84]
  [ 42  69  83]
  [ 40  68  81]
  ...
  [126 158 180]
  [125 156 179]
  [124 155 178]]

 [[ 42  69  83]
  [ 40  68  81]
  [ 39  67  80]
  ...
  [126 158 180]
  [125 156 179]
  [123 154 176]]

 [[ 43  67  79]
  [ 42  65  78]
  [ 41  64  76]
  ...
  [126 160 179]
  [123 157 179]
  [121 155 176]]

 ...

 [[100  48  40]
  [ 97  45  38]
  [ 96  44  37]
  ...
  [112 133 145]
  [123 142 153]
  [137 156 167]]

 [[125  52  38]
  [123  50  37]
  [122  52  38]
  ...
  [ 95 115 130]
  [104 124 139]
  [115 135 150]]

 [[137  64  51]
  [138  66  52]
  [138  67  53]
  ...
  [ 85 105 120]
  [ 88 108 123]
  [ 93 113 128]]]


[[[ 53  65  81]
  [ 51  64  80]
  [ 50  63  79]
  ...
  [133 155 179]
  [133 155 179]
  [132 154 178]]

 [[ 51  64  80]
  [ 50  63  79]
  [ 49  62  78]
  ...
  [134 156 180]
  [133 155 179]
  [131 153 176]]

 [[ 48  64  78]
  [ 47  63  76]
  [ 46  62  75]
  ...
  [129 156 177]
  [128 155 178]
  [127 153 176]]

 ...

 [[ 96  40  29]
  [ 97  41  30]
  [ 95  42  30]
  

[[[ 59  56  66]
  [ 62  58  68]
  [ 63  60  69]
  ...
  [113 159 170]
  [110 159 169]
  [108 157 168]]

 [[ 61  57  67]
  [ 62  58  68]
  [ 64  61  70]
  ...
  [114 161 171]
  [111 160 170]
  [111 160 170]]

 [[ 63  60  69]
  [ 63  60  69]
  [ 62  61  70]
  ...
  [116 164 172]
  [115 162 171]
  [114 161 170]]

 ...

 [[ 74  39  28]
  [ 75  40  30]
  [ 76  41  31]
  ...
  [203 220 231]
  [203 221 229]
  [203 221 229]]

 [[ 75  40  30]
  [ 75  40  30]
  [ 75  39  31]
  ...
  [206 221 232]
  [206 221 230]
  [205 220 229]]

 [[ 76  41  31]
  [ 76  41  31]
  [ 76  40  32]
  ...
  [206 221 232]
  [206 221 230]
  [206 221 230]]]


[[[ 36  50  56]
  [ 36  50  56]
  [ 36  49  58]
  ...
  [108 143 169]
  [108 143 169]
  [108 143 169]]

 [[ 35  48  55]
  [ 36  50  56]
  [ 37  50  59]
  ...
  [107 142 168]
  [107 142 168]
  [108 143 169]]

 [[ 30  49  53]
  [ 30  49  53]
  [ 34  50  56]
  ...
  [107 142 168]
  [107 142 168]
  [107 142 168]]

 ...

 [[ 63  39  27]
  [ 64  41  28]
  [ 65  41  31]
  

[[[ 45  54  68]
  [ 45  54  68]
  [ 45  54  68]
  ...
  [109 151 169]
  [112 151 170]
  [113 153 171]]

 [[ 44  53  67]
  [ 45  54  68]
  [ 45  54  68]
  ...
  [109 151 169]
  [113 153 171]
  [113 153 171]]

 [[ 43  51  66]
  [ 44  53  67]
  [ 45  55  67]
  ...
  [113 150 169]
  [114 151 170]
  [114 151 170]]

 ...

 [[ 73  44  35]
  [ 70  41  32]
  [ 68  39  30]
  ...
  [183 206 211]
  [184 207 212]
  [184 207 212]]

 [[ 75  43  32]
  [ 73  40  30]
  [ 72  39  28]
  ...
  [185 208 214]
  [185 208 214]
  [185 208 214]]

 [[ 74  41  31]
  [ 73  40  30]
  [ 72  39  28]
  ...
  [185 208 214]
  [185 208 214]
  [185 208 214]]]


[[[ 48  49  65]
  [ 49  50  66]
  [ 49  50  66]
  ...
  [112 147 164]
  [112 147 164]
  [112 147 164]]

 [[ 48  49  65]
  [ 48  49  65]
  [ 49  50  66]
  ...
  [112 147 164]
  [112 147 164]
  [113 148 165]]

 [[ 46  49  65]
  [ 47  51  66]
  [ 48  52  67]
  ...
  [114 146 165]
  [114 146 164]
  [114 146 164]]

 ...

 [[ 69  40  31]
  [ 66  37  28]
  [ 63  34  27]
  

[[[ 42  54  65]
  [ 43  55  67]
  [ 44  53  65]
  ...
  [117 147 165]
  [119 147 165]
  [119 147 165]]

 [[ 41  53  64]
  [ 42  54  65]
  [ 43  52  64]
  ...
  [117 147 165]
  [118 146 164]
  [118 146 164]]

 [[ 41  53  63]
  [ 41  53  63]
  [ 43  52  64]
  ...
  [114 146 164]
  [114 146 164]
  [112 145 163]]

 ...

 [[ 71  39  33]
  [ 70  38  32]
  [ 71  36  30]
  ...
  [171 200 209]
  [172 201 210]
  [173 202 211]]

 [[ 76  39  34]
  [ 76  39  34]
  [ 75  38  33]
  ...
  [172 201 210]
  [174 203 212]
  [174 203 212]]

 [[ 76  39  34]
  [ 76  39  34]
  [ 76  39  34]
  ...
  [172 201 210]
  [173 202 211]
  [174 203 212]]]


[[[ 45  49  58]
  [ 46  50  59]
  [ 49  53  61]
  ...
  [ 96 151 169]
  [ 95 150 168]
  [ 93 149 167]]

 [[ 45  49  58]
  [ 46  50  59]
  [ 48  52  60]
  ...
  [ 96 151 169]
  [ 95 150 168]
  [ 92 148 166]]

 [[ 46  50  60]
  [ 48  51  62]
  [ 49  52  63]
  ...
  [105 151 171]
  [102 150 169]
  [ 99 148 167]]

 ...

 [[ 73  35  32]
  [ 73  35  32]
  [ 73  35  32]
  

[[[  0 255 255]
  [  0 255 255]
  [  0 255 255]
  ...
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]]

 [[  0 255 255]
  [  0 255 255]
  [  0 255 255]
  ...
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]]

 [[  0 255 255]
  [  0 255 255]
  [  0 255 255]
  ...
  [118 151 169]
  [  0 255 255]
  [  0 255 255]]

 ...

 [[  0 255 255]
  [  0 255 255]
  [  0 255 255]
  ...
  [185 207 217]
  [  0 255 255]
  [  0 255 255]]

 [[  0 255 255]
  [  0 255 255]
  [  0 255 255]
  ...
  [185 207 217]
  [  0 255 255]
  [  0 255 255]]

 [[  0 255 255]
  [  0 255 255]
  [  0 255 255]
  ...
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]]]


[[[ 43  57  62]
  [ 43  57  62]
  [ 41  58  62]
  ...
  [103 151 171]
  [103 151 171]
  [102 150 169]]

 [[ 44  59  63]
  [ 45  60  64]
  [ 43  60  64]
  ...
  [103 151 171]
  [102 150 169]
  [102 150 169]]

 [[ 42  58  65]
  [ 43  59  66]
  [ 46  62  68]
  ...
  [105 151 171]
  [104 149 169]
  [104 149 169]]

 ...

 [[ 65  41  31]
  [ 65  41  31]
  [ 67  41  31]
  

[[[ 31  54  66]
  [ 32  55  67]
  [ 35  56  68]
  ...
  [110 148 169]
  [108 149 169]
  [107 148 168]]

 [[ 31  54  66]
  [ 32  55  67]
  [ 36  57  69]
  ...
  [109 147 168]
  [107 148 168]
  [107 148 168]]

 [[ 37  53  66]
  [ 39  55  68]
  [ 40  56  69]
  ...
  [111 147 168]
  [111 147 168]
  [111 147 168]]

 ...

 [[ 68  37  33]
  [ 67  36  32]
  [ 66  35  31]
  ...
  [186 207 212]
  [186 207 212]
  [187 208 214]]

 [[ 73  39  33]
  [ 71  36  30]
  [ 71  36  30]
  ...
  [186 207 212]
  [186 207 212]
  [187 208 214]]

 [[ 73  39  33]
  [ 72  37  32]
  [ 71  36  30]
  ...
  [185 206 211]
  [186 207 212]
  [186 207 212]]]


[[[ 39  50  59]
  [ 38  48  58]
  [ 38  48  58]
  ...
  [113 150 169]
  [113 150 169]
  [112 149 168]]

 [[ 39  50  59]
  [ 37  47  57]
  [ 37  47  57]
  ...
  [112 149 168]
  [112 149 168]
  [112 149 168]]

 [[ 37  50  59]
  [ 36  49  58]
  [ 36  49  58]
  ...
  [112 149 168]
  [111 148 167]
  [111 148 167]]

 ...

 [[ 69  39  34]
  [ 68  37  33]
  [ 68  37  33]
  

[[[ 47  53  61]
  [ 48  54  62]
  [ 46  55  62]
  ...
  [118 153 165]
  [118 153 165]
  [118 153 165]]

 [[ 46  52  60]
  [ 46  52  60]
  [ 43  52  60]
  ...
  [117 152 164]
  [117 152 164]
  [117 152 164]]

 [[ 42  51  59]
  [ 43  52  60]
  [ 42  50  60]
  ...
  [114 151 163]
  [117 152 164]
  [117 152 164]]

 ...

 [[ 65  39  36]
  [ 64  37  35]
  [ 65  36  34]
  ...
  [188 207 211]
  [190 207 211]
  [191 208 212]]

 [[ 67  39  34]
  [ 67  39  34]
  [ 67  36  32]
  ...
  [188 207 211]
  [189 208 212]
  [189 208 212]]

 [[ 68  40  36]
  [ 67  39  34]
  [ 68  37  33]
  ...
  [188 207 211]
  [188 207 211]
  [188 207 211]]]


[[[ 39  52  66]
  [ 36  50  64]
  [ 36  50  64]
  ...
  [116 151 170]
  [116 151 170]
  [116 151 170]]

 [[ 39  52  66]
  [ 37  51  65]
  [ 36  50  64]
  ...
  [115 150 169]
  [115 150 169]
  [115 150 169]]

 [[ 40  54  65]
  [ 39  53  64]
  [ 37  52  63]
  ...
  [110 149 168]
  [110 149 168]
  [110 149 168]]

 ...

 [[ 78  43  37]
  [ 75  41  35]
  [ 73  39  33]
  

[[[ 45  57  69]
  [ 45  57  69]
  [ 43  58  69]
  ...
  [120 150 170]
  [120 149 172]
  [119 148 171]]

 [[ 44  56  68]
  [ 44  56  68]
  [ 42  56  68]
  ...
  [120 150 170]
  [119 148 171]
  [119 148 171]]

 [[ 42  56  68]
  [ 43  58  69]
  [ 43  58  69]
  ...
  [119 149 169]
  [119 149 169]
  [118 148 168]]

 ...

 [[ 77  44  33]
  [ 75  43  32]
  [ 73  40  30]
  ...
  [178 209 211]
  [179 210 212]
  [180 211 213]]

 [[ 79  43  33]
  [ 77  42  32]
  [ 76  41  31]
  ...
  [181 210 212]
  [182 211 213]
  [182 211 213]]

 [[ 79  43  33]
  [ 79  43  33]
  [ 77  42  32]
  ...
  [181 210 212]
  [181 210 212]
  [182 211 213]]]


[[[ 41  54  70]
  [ 40  53  69]
  [ 40  53  69]
  ...
  [117 149 169]
  [117 149 169]
  [116 148 168]]

 [[ 40  53  69]
  [ 40  53  69]
  [ 39  51  68]
  ...
  [117 149 169]
  [116 148 168]
  [116 148 168]]

 [[ 37  52  68]
  [ 37  52  68]
  [ 37  53  66]
  ...
  [116 148 168]
  [116 148 168]
  [115 147 167]]

 ...

 [[ 76  42  29]
  [ 75  41  28]
  [ 73  38  26]
  

[[[ 34  55  65]
  [ 33  54  64]
  [ 36  55  65]
  ...
  [120 143 169]
  [122 143 167]
  [123 144 168]]

 [[ 33  54  64]
  [ 34  55  65]
  [ 37  56  67]
  ...
  [120 143 169]
  [122 143 167]
  [122 143 167]]

 [[ 38  55  64]
  [ 39  57  65]
  [ 40  58  66]
  ...
  [116 144 169]
  [119 144 170]
  [119 144 170]]

 ...

 [[ 75  42  34]
  [ 77  43  35]
  [ 75  42  34]
  ...
  [179 206 213]
  [180 207 214]
  [182 209 216]]

 [[ 80  44  36]
  [ 79  42  35]
  [ 79  42  35]
  ...
  [178 205 212]
  [180 207 214]
  [182 209 216]]

 [[ 82  46  38]
  [ 81  45  37]
  [ 80  44  36]
  ...
  [176 204 211]
  [179 206 213]
  [181 208 215]]]


[[[ 38  50  62]
  [ 39  51  63]
  [ 41  53  64]
  ...
  [121 146 165]
  [122 148 166]
  [122 148 166]]

 [[ 39  51  63]
  [ 41  53  64]
  [ 43  55  67]
  ...
  [121 146 165]
  [122 148 166]
  [123 149 167]]

 [[ 46  54  64]
  [ 47  55  65]
  [ 49  57  67]
  ...
  [119 146 167]
  [122 148 166]
  [123 149 167]]

 ...

 [[ 72  41  32]
  [ 72  41  32]
  [ 70  39  30]
  

[[[ 50  51  69]
  [ 52  53  71]
  [ 53  56  73]
  ...
  [115 152 176]
  [115 152 176]
  [115 152 176]]

 [[ 50  51  69]
  [ 51  52  70]
  [ 51  54  72]
  ...
  [113 151 174]
  [115 152 176]
  [115 152 176]]

 [[ 51  53  68]
  [ 52  54  69]
  [ 53  55  71]
  ...
  [115 151 174]
  [115 151 174]
  [115 151 174]]

 ...

 [[ 69  39  33]
  [ 67  37  30]
  [ 66  34  28]
  ...
  [178 208 212]
  [179 210 214]
  [180 211 215]]

 [[ 68  39  30]
  [ 67  38  29]
  [ 68  36  28]
  ...
  [178 208 212]
  [180 211 215]
  [181 212 216]]

 [[ 68  39  30]
  [ 67  38  29]
  [ 69  37  29]
  ...
  [178 208 212]
  [179 210 214]
  [180 211 215]]]


[[[ 44  60  69]
  [ 43  58  67]
  [ 39  57  65]
  ...
  [119 151 171]
  [118 150 170]
  [117 149 169]]

 [[ 43  58  67]
  [ 43  58  67]
  [ 39  57  65]
  ...
  [119 151 171]
  [118 150 170]
  [117 149 169]]

 [[ 41  59  67]
  [ 40  58  66]
  [ 39  56  67]
  ...
  [119 151 171]
  [118 150 170]
  [117 149 169]]

 ...

 [[ 67  39  27]
  [ 67  39  27]
  [ 66  40  28]
  

[[[ 42  52  69]
  [ 43  53  70]
  [ 44  55  69]
  ...
  [115 149 171]
  [114 148 169]
  [114 148 169]]

 [[ 39  50  66]
  [ 41  51  68]
  [ 42  53  67]
  ...
  [115 149 171]
  [114 148 169]
  [114 148 169]]

 [[ 41  52  66]
  [ 41  52  66]
  [ 42  53  67]
  ...
  [119 149 169]
  [118 148 168]
  [118 148 168]]

 ...

 [[ 68  47  34]
  [ 66  46  33]
  [ 66  43  31]
  ...
  [183 208 215]
  [184 209 216]
  [184 209 216]]

 [[ 72  46  34]
  [ 70  45  33]
  [ 68  43  31]
  ...
  [180 206 216]
  [183 207 217]
  [184 208 218]]

 [[ 72  46  34]
  [ 70  45  33]
  [ 69  44  32]
  ...
  [178 204 213]
  [182 206 216]
  [183 207 217]]]


[[[ 42  55  64]
  [ 43  56  65]
  [ 44  57  66]
  ...
  [118 145 173]
  [117 144 171]
  [116 143 170]]

 [[ 42  55  64]
  [ 44  57  66]
  [ 45  58  67]
  ...
  [118 145 173]
  [117 144 171]
  [116 143 170]]

 [[ 43  56  65]
  [ 45  58  67]
  [ 46  59  69]
  ...
  [121 147 172]
  [120 145 173]
  [119 144 171]]

 ...

 [[ 75  42  36]
  [ 73  41  35]
  [ 72  40  34]
  

[[[ 51  59  64]
  [ 53  60  65]
  [ 53  60  65]
  ...
  [116 147 169]
  [118 147 169]
  [118 147 169]]

 [[ 53  60  65]
  [ 54  61  67]
  [ 54  61  67]
  ...
  [115 146 168]
  [118 147 169]
  [118 147 169]]

 [[ 54  61  67]
  [ 54  61  67]
  [ 54  61  67]
  ...
  [113 147 167]
  [113 147 167]
  [113 147 167]]

 ...

 [[ 78  37  37]
  [ 75  34  34]
  [ 74  33  32]
  ...
  [182 203 213]
  [184 202 215]
  [184 202 215]]

 [[ 81  38  38]
  [ 78  35  35]
  [ 74  31  31]
  ...
  [186 205 216]
  [186 204 217]
  [185 203 216]]

 [[ 84  40  41]
  [ 80  37  37]
  [ 78  35  35]
  ...
  [187 206 217]
  [186 204 217]
  [186 204 217]]]


[[[ 33  58  65]
  [ 35  60  67]
  [ 40  62  70]
  ...
  [114 148 169]
  [115 149 171]
  [115 149 171]]

 [[ 35  60  67]
  [ 36  61  69]
  [ 40  62  70]
  ...
  [115 149 171]
  [115 149 171]
  [115 149 171]]

 [[ 41  59  67]
  [ 42  60  69]
  [ 44  61  70]
  ...
  [113 149 171]
  [113 149 171]
  [113 149 171]]

 ...

 [[ 72  39  36]
  [ 71  38  34]
  [ 69  36  32]
  

[[[ 48  58  70]
  [ 50  59  71]
  [ 50  59  71]
  ...
  [121 149 174]
  [123 151 174]
  [124 153 175]]

 [[ 50  59  71]
  [ 50  59  71]
  [ 50  59  71]
  ...
  [121 149 174]
  [124 153 175]
  [125 154 176]]

 [[ 51  60  74]
  [ 51  60  74]
  [ 50  58  73]
  ...
  [121 149 174]
  [125 150 176]
  [126 151 177]]

 ...

 [[ 74  44  37]
  [ 71  42  35]
  [ 69  39  33]
  ...
  [178 203 211]
  [181 206 213]
  [184 209 216]]

 [[ 78  43  37]
  [ 75  41  35]
  [ 73  39  33]
  ...
  [178 205 212]
  [180 207 214]
  [183 211 218]]

 [[ 77  42  36]
  [ 74  40  34]
  [ 73  39  33]
  ...
  [178 205 212]
  [180 207 214]
  [183 211 218]]]


[[[ 44  55  69]
  [ 44  55  69]
  [ 44  55  69]
  ...
  [121 151 171]
  [123 152 172]
  [123 152 172]]

 [[ 42  53  67]
  [ 42  53  67]
  [ 42  53  67]
  ...
  [123 152 172]
  [123 152 172]
  [123 152 172]]

 [[ 38  49  65]
  [ 39  50  66]
  [ 41  51  68]
  ...
  [123 152 172]
  [123 152 172]
  [123 152 172]]

 ...

 [[ 74  42  41]
  [ 71  40  38]
  [ 70  37  33]
  

[[[ 45  56  63]
  [ 48  60  67]
  [ 48  60  67]
  ...
  [111 152 173]
  [111 152 173]
  [111 152 173]]

 [[ 43  54  61]
  [ 45  56  63]
  [ 47  58  66]
  ...
  [110 151 172]
  [110 151 172]
  [111 152 173]]

 [[ 39  52  62]
  [ 43  56  65]
  [ 44  57  66]
  ...
  [109 150 171]
  [109 150 171]
  [110 151 172]]

 ...

 [[ 68  35  31]
  [ 65  32  29]
  [ 61  28  24]
  ...
  [182 206 216]
  [184 208 218]
  [185 209 219]]

 [[ 68  35  29]
  [ 65  33  27]
  [ 63  31  25]
  ...
  [183 207 217]
  [185 209 219]
  [187 211 220]]

 [[ 68  35  29]
  [ 66  34  28]
  [ 66  34  28]
  ...
  [184 208 218]
  [185 209 219]
  [187 211 220]]]


[[[ 41  56  65]
  [ 41  56  65]
  [ 43  58  67]
  ...
  [111 153 171]
  [110 152 170]
  [110 152 170]]

 [[ 40  55  64]
  [ 40  55  64]
  [ 41  56  65]
  ...
  [110 152 170]
  [110 152 170]
  [110 152 170]]

 [[ 37  54  63]
  [ 37  54  63]
  [ 39  57  65]
  ...
  [112 152 169]
  [112 152 169]
  [111 151 167]]

 ...

 [[ 67  39  26]
  [ 64  37  23]
  [ 64  34  23]
  

[[[  0 255 255]
  [  0 255 255]
  [  0 255 255]
  ...
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]]

 [[  0 255 255]
  [  0 255 255]
  [  0 255 255]
  ...
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]]

 [[  0 255 255]
  [  0 255 255]
  [  0 255 255]
  ...
  [109 146 170]
  [  0 255 255]
  [  0 255 255]]

 ...

 [[  0 255 255]
  [  0 255 255]
  [  0 255 255]
  ...
  [181 206 213]
  [  0 255 255]
  [  0 255 255]]

 [[  0 255 255]
  [  0 255 255]
  [  0 255 255]
  ...
  [181 206 213]
  [  0 255 255]
  [  0 255 255]]

 [[  0 255 255]
  [  0 255 255]
  [  0 255 255]
  ...
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]]]


[[[  0 255 255]
  [  0 255 255]
  [  0 255 255]
  ...
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]]

 [[  0 255 255]
  [  0 255 255]
  [  0 255 255]
  ...
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]]

 [[  0 255 255]
  [  0 255 255]
  [  0 255 255]
  ...
  [110 146 167]
  [  0 255 255]
  [  0 255 255]]

 ...

 [[  0 255 255]
  [  0 255 255]
  [  0 255 255]
  

[[[ 43  53  63]
  [ 41  52  62]
  [ 40  51  60]
  ...
  [118 149 165]
  [118 149 165]
  [119 150 166]]

 [[ 41  52  62]
  [ 41  52  62]
  [ 40  51  60]
  ...
  [118 149 165]
  [118 149 165]
  [119 150 166]]

 [[ 43  51  62]
  [ 43  51  62]
  [ 43  51  62]
  ...
  [119 151 164]
  [119 151 164]
  [119 151 164]]

 ...

 [[ 72  42  31]
  [ 72  42  31]
  [ 72  42  31]
  ...
  [176 204 209]
  [176 204 209]
  [178 206 210]]

 [[ 77  42  32]
  [ 77  42  32]
  [ 79  43  33]
  ...
  [176 204 211]
  [176 204 211]
  [176 204 211]]

 [[ 77  42  32]
  [ 77  42  32]
  [ 80  44  34]
  ...
  [175 202 209]
  [175 202 209]
  [176 204 211]]]


[[[ 52  63  78]
  [ 52  63  78]
  [ 52  63  78]
  ...
  [128 173 181]
  [128 173 181]
  [128 173 181]]

 [[ 50  61  75]
  [ 51  62  76]
  [ 52  63  78]
  ...
  [129 174 182]
  [129 174 182]
  [129 174 182]]

 [[ 48  59  73]
  [ 50  61  75]
  [ 51  62  76]
  ...
  [133 173 182]
  [132 172 181]
  [132 172 181]]

 ...

 [[ 84  44  34]
  [ 85  45  35]
  [ 85  45  35]
  

[[[ 50  59  71]
  [ 50  59  71]
  [ 52  64  76]
  ...
  [127 162 186]
  [126 161 185]
  [126 161 185]]

 [[ 53  63  75]
  [ 52  62  74]
  [ 51  63  75]
  ...
  [127 162 186]
  [127 162 186]
  [127 162 186]]

 [[ 58  67  79]
  [ 57  66  78]
  [ 54  64  76]
  ...
  [128 164 186]
  [128 164 186]
  [127 163 185]]

 ...

 [[ 87  46  41]
  [ 87  46  41]
  [ 87  46  41]
  ...
  [201 226 231]
  [201 226 231]
  [201 226 231]]

 [[ 90  44  38]
  [ 91  46  39]
  [ 91  46  39]
  ...
  [199 226 233]
  [199 226 233]
  [199 226 233]]

 [[ 90  44  38]
  [ 91  46  39]
  [ 91  46  39]
  ...
  [199 226 233]
  [199 226 233]
  [200 227 234]]]


[[[ 43  62  72]
  [ 43  62  72]
  [ 43  65  75]
  ...
  [120 165 180]
  [118 165 180]
  [117 164 179]]

 [[ 45  64  75]
  [ 45  64  75]
  [ 44  66  76]
  ...
  [121 166 181]
  [118 165 180]
  [118 165 180]]

 [[ 51  67  78]
  [ 49  66  77]
  [ 49  66  77]
  ...
  [123 165 181]
  [123 165 181]
  [122 164 180]]

 ...

 [[ 79  42  35]
  [ 79  42  35]
  [ 79  42  35]
  

[[[ 48  63  65]
  [ 49  64  66]
  [ 49  63  68]
  ...
  [132 165 182]
  [131 164 181]
  [129 162 179]]

 [[ 46  62  64]
  [ 48  63  65]
  [ 48  62  67]
  ...
  [135 167 185]
  [132 165 182]
  [130 163 180]]

 [[ 46  61  65]
  [ 46  61  65]
  [ 50  62  67]
  ...
  [137 166 186]
  [134 164 184]
  [133 163 183]]

 ...

 [[ 76  46  41]
  [ 77  47  43]
  [ 77  47  43]
  ...
  [209 230 236]
  [207 228 233]
  [206 227 232]]

 [[ 81  46  43]
  [ 82  47  44]
  [ 81  46  43]
  ...
  [206 229 235]
  [205 227 235]
  [204 226 234]]

 [[ 82  47  44]
  [ 82  47  44]
  [ 81  46  43]
  ...
  [204 227 232]
  [203 225 233]
  [203 225 233]]]


[[[ 52  65  74]
  [ 53  66  76]
  [ 55  66  76]
  ...
  [135 165 190]
  [135 165 190]
  [135 165 190]]

 [[ 50  63  72]
  [ 51  64  73]
  [ 53  64  73]
  ...
  [133 164 188]
  [135 165 190]
  [135 165 190]]

 [[ 48  61  68]
  [ 49  62  69]
  [ 52  62  72]
  ...
  [133 161 186]
  [134 162 187]
  [134 162 187]]

 ...

 [[ 84  47  42]
  [ 83  46  41]
  [ 82  45  40]
  

[[[ 52  65  74]
  [ 53  66  76]
  [ 53  66  76]
  ...
  [136 163 184]
  [136 163 184]
  [135 162 183]]

 [[ 52  65  74]
  [ 52  65  74]
  [ 55  67  77]
  ...
  [135 162 183]
  [135 162 183]
  [134 161 182]]

 [[ 49  64  73]
  [ 49  64  73]
  [ 51  67  76]
  ...
  [135 163 181]
  [134 162 180]
  [134 162 180]]

 ...

 [[ 91  46  38]
  [ 91  46  38]
  [ 89  47  38]
  ...
  [202 222 230]
  [202 222 230]
  [202 222 230]]

 [[ 95  46  36]
  [ 94  45  35]
  [ 92  46  35]
  ...
  [198 220 230]
  [199 221 231]
  [199 221 231]]

 [[ 96  48  37]
  [ 96  48  37]
  [ 94  48  37]
  ...
  [196 217 227]
  [197 218 228]
  [198 220 230]]]


[[[ 51  64  73]
  [ 51  64  73]
  [ 51  64  73]
  ...
  [134 165 182]
  [135 163 181]
  [135 163 181]]

 [[ 51  64  73]
  [ 51  64  73]
  [ 52  65  74]
  ...
  [133 164 181]
  [134 162 180]
  [134 162 180]]

 [[ 53  63  75]
  [ 53  63  75]
  [ 54  65  74]
  ...
  [132 162 182]
  [132 162 180]
  [131 161 179]]

 ...

 [[ 90  44  31]
  [ 91  45  32]
  [ 91  45  32]
  

[[[ 44  61  70]
  [ 42  60  69]
  [ 42  60  69]
  ...
  [122 158 181]
  [121 156 180]
  [121 156 180]]

 [[ 41  59  67]
  [ 40  58  66]
  [ 41  59  67]
  ...
  [124 159 183]
  [122 158 181]
  [121 156 180]]

 [[ 39  57  63]
  [ 40  59  65]
  [ 40  59  65]
  ...
  [125 162 181]
  [124 160 179]
  [122 159 178]]

 ...

 [[ 89  42  40]
  [ 89  42  40]
  [ 87  42  40]
  ...
  [196 222 225]
  [195 220 225]
  [194 219 224]]

 [[ 90  43  41]
  [ 90  43  41]
  [ 90  43  41]
  ...
  [201 225 230]
  [198 224 229]
  [197 223 228]]

 [[ 92  45  44]
  [ 94  46  45]
  [ 94  46  45]
  ...
  [203 226 231]
  [199 225 230]
  [199 225 230]]]


[[[ 40  56  62]
  [ 42  58  65]
  [ 44  60  69]
  ...
  [134 164 184]
  [133 162 185]
  [132 161 183]]

 [[ 40  56  62]
  [ 41  57  63]
  [ 42  57  66]
  ...
  [134 164 184]
  [133 162 185]
  [132 161 183]]

 [[ 40  56  62]
  [ 41  57  63]
  [ 41  57  63]
  ...
  [132 163 186]
  [131 162 185]
  [130 161 183]]

 ...

 [[ 87  42  40]
  [ 86  41  39]
  [ 85  40  38]
  

[[[ 44  57  66]
  [ 42  55  64]
  [ 41  53  63]
  ...
  [119 156 175]
  [116 154 175]
  [115 153 174]]

 [[ 44  57  66]
  [ 43  56  65]
  [ 42  55  64]
  ...
  [118 155 174]
  [115 153 174]
  [115 153 174]]

 [[ 44  57  66]
  [ 44  57  66]
  [ 44  57  66]
  ...
  [113 153 170]
  [111 154 170]
  [111 154 170]]

 ...

 [[ 83  64  53]
  [ 82  63  52]
  [ 80  60  50]
  ...
  [157 170 179]
  [158 170 182]
  [161 173 184]]

 [[ 78  59  49]
  [ 76  57  46]
  [ 77  55  45]
  ...
  [160 170 182]
  [161 171 183]
  [164 173 185]]

 [[ 71  52  42]
  [ 70  51  41]
  [ 71  49  39]
  ...
  [163 172 184]
  [164 173 185]
  [166 176 188]]]


[[[ 55  58  69]
  [ 53  57  67]
  [ 51  57  67]
  ...
  [132 159 175]
  [134 158 175]
  [134 158 175]]

 [[ 55  58  69]
  [ 53  57  67]
  [ 53  58  69]
  ...
  [132 159 175]
  [134 158 175]
  [136 160 176]]

 [[ 53  58  69]
  [ 51  57  67]
  [ 53  58  69]
  ...
  [130 159 175]
  [134 160 176]
  [134 160 176]]

 ...

 [[ 82  52  46]
  [ 80  50  43]
  [ 76  46  40]
  

[[[ 54  58  71]
  [ 56  61  74]
  [ 57  62  75]
  ...
  [126 157 181]
  [126 158 180]
  [126 158 180]]

 [[ 55  60  72]
  [ 56  61  74]
  [ 56  61  74]
  ...
  [126 157 181]
  [126 158 180]
  [126 158 180]]

 [[ 55  60  71]
  [ 56  62  72]
  [ 56  62  72]
  ...
  [121 157 179]
  [121 157 179]
  [121 157 179]]

 ...

 [[ 86  61  54]
  [ 87  62  55]
  [ 86  61  54]
  ...
  [150 170 178]
  [150 170 178]
  [151 171 179]]

 [[ 79  57  49]
  [ 79  57  49]
  [ 78  56  48]
  ...
  [154 172 180]
  [154 172 180]
  [154 172 180]]

 [[ 73  51  43]
  [ 73  51  43]
  [ 72  50  42]
  ...
  [158 175 184]
  [158 175 184]
  [158 175 184]]]


[[[ 56  58  71]
  [ 57  59  72]
  [ 57  59  72]
  ...
  [126 161 178]
  [124 160 175]
  [124 160 175]]

 [[ 57  59  72]
  [ 58  60  74]
  [ 58  60  74]
  ...
  [126 161 178]
  [124 160 175]
  [124 160 175]]

 [[ 58  61  72]
  [ 59  62  73]
  [ 59  62  73]
  ...
  [126 159 177]
  [126 159 177]
  [125 158 176]]

 ...

 [[ 82  64  49]
  [ 82  64  49]
  [ 79  64  48]
  

[[[ 41  50  65]
  [ 43  51  66]
  [ 43  51  66]
  ...
  [120 156 178]
  [122 156 178]
  [123 157 179]]

 [[ 40  49  64]
  [ 40  49  64]
  [ 41  50  65]
  ...
  [121 157 179]
  [123 157 179]
  [123 157 179]]

 [[ 40  50  62]
  [ 40  50  62]
  [ 41  51  63]
  ...
  [121 158 177]
  [121 158 177]
  [121 158 177]]

 ...

 [[ 63  41  40]
  [ 60  37  36]
  [ 61  36  35]
  ...
  [158 178 186]
  [160 181 187]
  [163 183 189]]

 [[ 67  41  38]
  [ 65  39  36]
  [ 64  37  35]
  ...
  [154 176 184]
  [157 177 185]
  [159 179 187]]

 [[ 68  42  39]
  [ 66  40  37]
  [ 65  39  36]
  ...
  [152 175 183]
  [156 176 184]
  [157 177 185]]]


[[[ 44  55  69]
  [ 44  55  69]
  [ 44  55  69]
  ...
  [130 158 181]
  [130 158 181]
  [131 160 182]]

 [[ 37  48  62]
  [ 39  51  65]
  [ 39  51  65]
  ...
  [128 157 180]
  [128 157 180]
  [128 157 180]]

 [[ 35  45  62]
  [ 36  46  63]
  [ 36  49  65]
  ...
  [125 156 179]
  [125 156 179]
  [125 156 179]]

 ...

 [[ 64  40  37]
  [ 63  39  36]
  [ 63  39  36]
  

[[[ 51  65  72]
  [ 52  66  73]
  [ 52  66  73]
  ...
  [128 156 174]
  [129 157 176]
  [130 158 177]]

 [[ 51  65  72]
  [ 52  66  73]
  [ 52  66  73]
  ...
  [128 156 174]
  [129 157 176]
  [129 157 176]]

 [[ 55  64  72]
  [ 56  65  73]
  [ 55  67  74]
  ...
  [127 155 173]
  [128 156 174]
  [128 156 174]]

 ...

 [[ 88  49  37]
  [ 87  48  36]
  [ 84  47  35]
  ...
  [191 210 216]
  [191 210 216]
  [193 211 217]]

 [[ 85  48  36]
  [ 84  47  35]
  [ 83  46  34]
  ...
  [189 212 217]
  [192 213 218]
  [193 214 219]]

 [[ 84  47  35]
  [ 84  47  35]
  [ 84  47  35]
  ...
  [190 213 218]
  [194 215 221]
  [195 216 222]]]


[[[ 54  58  71]
  [ 55  60  72]
  [ 56  61  74]
  ...
  [131 159 172]
  [131 159 172]
  [131 159 172]]

 [[ 55  60  72]
  [ 56  61  74]
  [ 56  61  74]
  ...
  [131 159 172]
  [131 159 172]
  [131 159 172]]

 [[ 58  60  74]
  [ 58  60  74]
  [ 59  62  75]
  ...
  [133 157 174]
  [133 157 174]
  [132 156 173]]

 ...

 [[ 89  46  32]
  [ 89  46  32]
  [ 89  46  32]
  

[[[ 91 109 136]
  [ 91 109 136]
  [ 91 109 138]
  ...
  [ 96 129 146]
  [ 96 130 145]
  [ 97 131 146]]

 [[ 92 111 137]
  [ 92 111 137]
  [ 92 110 139]
  ...
  [ 96 129 146]
  [ 96 130 145]
  [ 96 130 145]]

 [[ 97 113 140]
  [ 97 113 140]
  [ 95 111 138]
  ...
  [ 98 129 146]
  [ 97 127 145]
  [ 97 127 145]]

 ...

 [[ 38  42  51]
  [ 37  41  49]
  [ 36  40  48]
  ...
  [ 26  26  26]
  [ 23  23  23]
  [ 23  23  23]]

 [[ 38  40  47]
  [ 38  40  47]
  [ 36  38  44]
  ...
  [ 26  24  24]
  [ 24  22  22]
  [ 23  21  21]]

 [[ 37  39  46]
  [ 36  38  44]
  [ 34  37  43]
  ...
  [ 23  21  21]
  [ 18  16  16]
  [ 20  17  17]]]


[[[107 148 175]
  [107 148 175]
  [108 149 176]
  ...
  [123 142 166]
  [124 143 167]
  [126 145 169]]

 [[107 148 175]
  [106 147 174]
  [106 147 174]
  ...
  [120 139 164]
  [121 141 165]
  [123 142 166]]

 [[109 149 172]
  [108 148 171]
  [105 146 171]
  ...
  [113 139 162]
  [113 139 162]
  [114 141 164]]

 ...

 [[ 59  61  68]
  [ 58  60  67]
  [ 55  57  66]
  

[[[240 255 255]
  [240 255 255]
  [240 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[240 255 255]
  [240 255 255]
  [240 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[240 255 255]
  [240 255 255]
  [240 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[ 65  78  94]
  [ 64  77  93]
  [ 64  77  93]
  ...
  [ 26  26  33]
  [ 28  28  35]
  [ 29  29  36]]

 [[ 67  79  95]
  [ 65  78  94]
  [ 64  77  93]
  ...
  [ 30  26  38]
  [ 33  29  39]
  [ 33  29  39]]

 [[ 68  80  97]
  [ 67  79  95]
  [ 65  78  94]
  ...
  [ 33  29  41]
  [ 33  29  39]
  [ 31  28  38]]]


[[[  0 255 255]
  [  0 255 255]
  [  0 255 255]
  ...
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]]

 [[  0 255 255]
  [  0 255 255]
  [  0 255 255]
  ...
  [  0 255 255]
  [  0 255 255]
  [  0 255 255]]

 [[  0 255 255]
  [  0 255 255]
  [  0 255 255]
  ...
  [255 255 255]
  [  0 255 255]
  [  0 255 255]]

 ...

 [[  0 255 255]
  [  0 255 255]
  [  0 255 255]
  

[[[ 90 123 154]
  [ 87 120 151]
  [ 87 119 153]
  ...
  [209 240 255]
  [208 239 254]
  [209 240 255]]

 [[ 91 124 155]
  [ 90 123 154]
  [ 89 121 154]
  ...
  [209 240 255]
  [209 240 255]
  [209 240 255]]

 [[ 93 123 155]
  [ 92 122 154]
  [ 92 122 154]
  ...
  [209 240 255]
  [209 241 254]
  [209 241 254]]

 ...

 [[ 27  70  90]
  [ 41  84 104]
  [ 65 103 120]
  ...
  [ 19  32  28]
  [ 16  28  24]
  [ 19  32  28]]

 [[ 28  75  92]
  [ 44  91 108]
  [ 68 108 124]
  ...
  [ 19  31  29]
  [ 16  30  28]
  [ 18  33  30]]

 [[ 34  80  98]
  [ 53  99 117]
  [ 73 113 129]
  ...
  [ 21  33  31]
  [ 18  33  30]
  [ 19  34  31]]]


[[[ 52  67  97]
  [ 51  66  96]
  [ 51  67  94]
  ...
  [102 141 167]
  [103 142 168]
  [103 142 168]]

 [[ 52  67  97]
  [ 51  66  96]
  [ 52  68  95]
  ...
  [102 141 167]
  [103 142 168]
  [103 142 168]]

 [[ 54  69  96]
  [ 52  68  95]
  [ 54  69  96]
  ...
  [100 142 167]
  [103 142 168]
  [103 142 168]]

 ...

 [[ 11   8  22]
  [  8   6  20]
  [  5   4  21]
  

[[[ 69  75  92]
  [ 69  75  92]
  [ 70  76  93]
  ...
  [ 86 105 116]
  [ 87 106 117]
  [ 88 107 118]]

 [[ 71  77  94]
  [ 71  77  94]
  [ 71  77  94]
  ...
  [ 87 106 117]
  [ 87 106 117]
  [ 88 107 118]]

 [[ 74  79  97]
  [ 74  79  97]
  [ 71  77  94]
  ...
  [ 85 106 118]
  [ 86 107 119]
  [ 86 107 119]]

 ...

 [[  7  12  36]
  [  8  13  37]
  [  9  14  39]
  ...
  [198 212 225]
  [200 211 225]
  [199 210 224]]

 [[  9  12  36]
  [ 10  13  37]
  [ 11  14  39]
  ...
  [201 212 227]
  [200 211 225]
  [199 210 224]]

 [[ 10  13  37]
  [ 11  14  39]
  [ 12  15  40]
  ...
  [202 214 228]
  [201 212 227]
  [200 211 225]]]


[[[ 74  84  96]
  [ 74  84  96]
  [ 73  82  95]
  ...
  [ 97 105 127]
  [ 95 104 125]
  [ 95 104 125]]

 [[ 73  82  95]
  [ 73  82  95]
  [ 73  82  95]
  ...
  [ 95 104 125]
  [ 95 104 125]
  [ 94 103 124]]

 [[ 73  83  93]
  [ 73  83  93]
  [ 73  82  95]
  ...
  [ 93 104 125]
  [ 93 104 125]
  [ 92 103 124]]

 ...

 [[ 16  17  42]
  [ 20  21  46]
  [ 22  23  48]
  

[[[ 68  82 102]
  [ 67  80 101]
  [ 68  82 102]
  ...
  [ 84 108 127]
  [ 84 108 127]
  [ 83 106 125]]

 [[ 67  80 101]
  [ 67  80 101]
  [ 67  80 101]
  ...
  [ 84 108 127]
  [ 83 106 125]
  [ 82 105 124]]

 [[ 65  81 101]
  [ 64  80 100]
  [ 67  80 101]
  ...
  [ 86 107 127]
  [ 82 105 124]
  [ 81 104 123]]

 ...

 [[  7  17  42]
  [  6  16  41]
  [  6  15  43]
  ...
  [206 214 229]
  [207 216 230]
  [208 217 231]]

 [[  9  16  42]
  [  9  16  42]
  [ 10  17  44]
  ...
  [205 216 230]
  [206 217 231]
  [207 218 232]]

 [[ 10  17  44]
  [ 10  17  44]
  [ 12  19  45]
  ...
  [206 217 231]
  [207 218 232]
  [207 218 232]]]


[[[ 96  99 124]
  [101 104 128]
  [104 108 130]
  ...
  [107 124 141]
  [110 124 142]
  [111 125 144]]

 [[ 96  99 124]
  [ 99 103 127]
  [101 104 127]
  ...
  [109 126 144]
  [112 127 145]
  [113 128 146]]

 [[ 93  99 121]
  [ 94 100 122]
  [ 95 101 123]
  ...
  [108 127 145]
  [111 127 148]
  [111 127 148]]

 ...

 [[ 26  28  57]
  [ 27  29  58]
  [ 28  30  59]
  

[[[ 54  59  70]
  [ 55  60  71]
  [ 52  60  70]
  ...
  [ 83  99 124]
  [ 79  99 123]
  [ 78  97 122]]

 [[ 55  60  71]
  [ 55  60  71]
  [ 52  60  70]
  ...
  [ 83  99 124]
  [ 78  97 122]
  [ 77  96 120]]

 [[ 53  60  72]
  [ 54  61  74]
  [ 51  60  72]
  ...
  [ 84 101 124]
  [ 81  99 121]
  [ 80  98 120]]

 ...

 [[255 226 177]
  [255 225 176]
  [255 222 171]
  ...
  [135 168 179]
  [137 169 182]
  [139 171 184]]

 [[255 229 177]
  [254 228 176]
  [253 226 173]
  ...
  [136 167 178]
  [137 168 179]
  [141 171 182]]

 [[254 228 176]
  [254 228 176]
  [253 226 173]
  ...
  [136 167 178]
  [137 168 179]
  [141 171 182]]]


[[[ 35  41  58]
  [ 35  41  58]
  [ 35  41  58]
  ...
  [ 91 120 143]
  [ 90 119 141]
  [ 90 119 141]]

 [[ 35  41  58]
  [ 34  40  57]
  [ 35  41  58]
  ...
  [ 91 120 143]
  [ 91 120 143]
  [ 90 119 141]]

 [[ 41  41  59]
  [ 41  41  59]
  [ 41  41  59]
  ...
  [ 88 119 141]
  [ 88 119 141]
  [ 88 119 141]]

 ...

 [[127 255 212]
  [127 255 212]
  [127 255 212]
  

[[[ 36  51  62]
  [ 37  52  63]
  [ 40  54  65]
  ...
  [140 166 196]
  [137 165 197]
  [136 164 196]]

 [[ 37  52  63]
  [ 39  53  64]
  [ 41  55  67]
  ...
  [139 165 195]
  [136 164 196]
  [135 163 194]]

 [[ 41  53  64]
  [ 43  55  67]
  [ 44  56  68]
  ...
  [135 163 193]
  [131 163 192]
  [130 161 190]]

 ...

 [[ 29  33  41]
  [ 27  31  39]
  [ 25  29  38]
  ...
  [116 132 161]
  [118 133 162]
  [118 133 162]]

 [[ 29  34  40]
  [ 27  31  37]
  [ 27  30  36]
  ...
  [120 132 162]
  [123 134 162]
  [123 134 162]]

 [[ 28  33  39]
  [ 27  31  37]
  [ 27  30  36]
  ...
  [123 136 166]
  [126 137 165]
  [126 137 165]]]


[[[ 34  57  62]
  [ 35  58  63]
  [ 36  59  65]
  ...
  [133 167 194]
  [131 165 191]
  [127 161 188]]

 [[ 35  58  63]
  [ 34  57  62]
  [ 33  56  61]
  ...
  [132 166 192]
  [128 163 189]
  [126 160 187]]

 [[ 36  57  62]
  [ 35  55  61]
  [ 31  52  58]
  ...
  [129 164 190]
  [127 161 188]
  [125 159 185]]

 ...

 [[ 26  28  30]
  [ 26  28  30]
  [ 26  27  31]
  

[[[ 47  62  78]
  [ 47  62  78]
  [ 47  62  78]
  ...
  [139 175 196]
  [140 176 197]
  [140 176 197]]

 [[ 47  62  78]
  [ 47  62  78]
  [ 46  61  77]
  ...
  [139 175 196]
  [138 174 195]
  [139 175 196]]

 [[ 49  62  78]
  [ 49  62  78]
  [ 49  62  78]
  ...
  [138 174 195]
  [136 172 194]
  [136 172 194]]

 ...

 [[ 38  34  32]
  [ 35  31  30]
  [ 35  31  30]
  ...
  [162 165 190]
  [164 165 190]
  [165 166 191]]

 [[ 37  33  31]
  [ 34  30  29]
  [ 35  31  30]
  ...
  [162 166 188]
  [164 167 187]
  [165 168 188]]

 [[ 35  31  30]
  [ 35  31  30]
  [ 35  31  30]
  ...
  [163 167 189]
  [164 167 187]
  [165 168 188]]]


[[[ 46  65  78]
  [ 46  65  78]
  [ 46  65  78]
  ...
  [140 172 197]
  [138 171 195]
  [137 170 194]]

 [[ 47  66  79]
  [ 49  67  80]
  [ 49  67  80]
  ...
  [141 174 198]
  [140 172 197]
  [138 171 195]]

 [[ 50  67  83]
  [ 51  68  84]
  [ 52  70  85]
  ...
  [143 174 196]
  [143 174 196]
  [143 174 196]]

 ...

 [[ 36  30  40]
  [ 36  30  40]
  [ 35  32  41]
  

[[[ 51  59  76]
  [ 53  61  78]
  [ 55  63  80]
  ...
  [133 174 199]
  [129 173 198]
  [127 171 196]]

 [[ 51  59  76]
  [ 53  61  78]
  [ 54  62  79]
  ...
  [134 175 201]
  [131 175 199]
  [128 172 197]]

 [[ 52  61  75]
  [ 53  62  76]
  [ 54  62  79]
  ...
  [138 177 203]
  [136 175 201]
  [133 173 198]]

 ...

 [[ 35  29  35]
  [ 38  31  37]
  [ 39  33  38]
  ...
  [159 170 191]
  [160 171 192]
  [159 170 191]]

 [[ 34  28  33]
  [ 38  31  37]
  [ 39  33  37]
  ...
  [159 170 191]
  [159 170 189]
  [157 169 188]]

 [[ 37  30  36]
  [ 38  31  37]
  [ 40  35  38]
  ...
  [160 171 192]
  [159 170 189]
  [159 170 189]]]


[[[ 40  61  78]
  [ 41  63  80]
  [ 42  64  81]
  ...
  [150 176 201]
  [147 175 200]
  [145 173 198]]

 [[ 39  60  77]
  [ 41  63  80]
  [ 41  63  80]
  ...
  [150 176 201]
  [146 174 199]
  [145 173 198]]

 [[ 40  61  78]
  [ 41  63  80]
  [ 42  64  81]
  ...
  [149 175 200]
  [146 174 199]
  [144 172 197]]

 ...

 [[ 33  31  36]
  [ 35  33  38]
  [ 36  34  39]
  

[[[ 42  64  72]
  [ 43  65  73]
  [ 49  69  77]
  ...
  [141 173 199]
  [140 172 198]
  [140 172 198]]

 [[ 41  63  71]
  [ 43  65  73]
  [ 47  67  76]
  ...
  [141 173 199]
  [140 172 198]
  [138 170 197]]

 [[ 46  65  78]
  [ 47  66  79]
  [ 49  68  78]
  ...
  [141 174 198]
  [138 171 195]
  [137 170 194]]

 ...

 [[ 44  34  38]
  [ 42  31  35]
  [ 41  30  34]
  ...
  [157 169 188]
  [157 169 188]
  [157 169 188]]

 [[ 42  34  38]
  [ 41  33  37]
  [ 41  33  37]
  ...
  [157 169 188]
  [159 170 186]
  [161 171 187]]

 [[ 43  35  39]
  [ 42  34  38]
  [ 42  34  38]
  ...
  [159 170 189]
  [161 171 187]
  [161 171 187]]]


[[[ 49  63  75]
  [ 50  65  76]
  [ 51  66  77]
  ...
  [137 176 202]
  [135 173 201]
  [132 171 199]]

 [[ 50  65  76]
  [ 51  66  77]
  [ 51  66  77]
  ...
  [137 176 202]
  [135 173 201]
  [133 172 200]]

 [[ 55  67  78]
  [ 55  67  78]
  [ 53  67  78]
  ...
  [137 176 202]
  [136 175 201]
  [135 174 199]]

 ...

 [[ 41  36  37]
  [ 40  35  36]
  [ 40  35  38]
  

[[[ 49  65  72]
  [ 51  67  74]
  [ 53  68  77]
  ...
  [134 171 197]
  [136 172 195]
  [136 172 195]]

 [[ 50  66  73]
  [ 51  67  74]
  [ 53  68  77]
  ...
  [133 170 196]
  [135 170 194]
  [134 169 193]]

 [[ 49  68  74]
  [ 51  69  75]
  [ 53  69  75]
  ...
  [131 168 192]
  [133 168 192]
  [133 168 192]]

 ...

 [[ 36  36  36]
  [ 35  35  35]
  [ 34  34  34]
  ...
  [154 169 194]
  [154 170 192]
  [154 170 192]]

 [[ 36  36  36]
  [ 35  35  35]
  [ 34  35  32]
  ...
  [157 169 192]
  [157 170 191]
  [157 170 191]]

 [[ 34  34  34]
  [ 34  34  34]
  [ 34  35  32]
  ...
  [157 169 192]
  [158 171 192]
  [158 171 192]]]


[[[ 62  68  85]
  [ 61  67  84]
  [ 58  66  83]
  ...
  [138 172 198]
  [140 172 198]
  [140 172 198]]

 [[ 61  67  84]
  [ 61  67  84]
  [ 58  66  83]
  ...
  [138 172 198]
  [140 172 198]
  [138 170 197]]

 [[ 62  66  81]
  [ 62  66  81]
  [ 59  65  80]
  ...
  [138 173 197]
  [140 172 197]
  [138 171 195]]

 ...

 [[ 37  36  39]
  [ 37  36  39]
  [ 36  35  38]
  

[[[ 54  61  81]
  [ 53  60  80]
  [ 50  59  78]
  ...
  [141 168 196]
  [141 168 196]
  [141 168 196]]

 [[ 55  63  82]
  [ 54  61  81]
  [ 50  59  78]
  ...
  [140 167 195]
  [140 167 195]
  [140 167 195]]

 [[ 54  61  81]
  [ 53  60  80]
  [ 52  59  78]
  ...
  [140 167 195]
  [140 167 195]
  [140 167 195]]

 ...

 [[ 28  30  32]
  [ 28  30  32]
  [ 28  30  32]
  ...
  [157 169 188]
  [157 170 186]
  [156 169 185]]

 [[ 30  29  32]
  [ 30  29  32]
  [ 30  29  32]
  ...
  [159 171 187]
  [159 171 187]
  [159 171 187]]

 [[ 33  32  34]
  [ 31  31  33]
  [ 31  31  33]
  ...
  [160 172 189]
  [160 172 189]
  [161 174 190]]]


[[[ 44  62  75]
  [ 44  62  75]
  [ 45  63  76]
  ...
  [133 168 199]
  [133 168 199]
  [133 168 199]]

 [[ 45  63  76]
  [ 45  63  76]
  [ 45  63  76]
  ...
  [133 168 199]
  [132 167 198]
  [132 167 198]]

 [[ 42  65  78]
  [ 42  65  78]
  [ 41  64  76]
  ...
  [134 168 196]
  [134 168 196]
  [133 166 195]]

 ...

 [[ 33  32  34]
  [ 31  31  33]
  [ 31  31  33]
  

[[[ 48  68  83]
  [ 45  65  80]
  [ 43  63  78]
  ...
  [135 174 199]
  [135 174 199]
  [135 174 199]]

 [[ 48  68  83]
  [ 45  65  80]
  [ 43  63  78]
  ...
  [135 174 199]
  [135 174 199]
  [135 174 199]]

 [[ 51  67  80]
  [ 48  64  78]
  [ 45  63  78]
  ...
  [135 175 198]
  [135 175 198]
  [135 175 198]]

 ...

 [[ 38  35  38]
  [ 38  35  38]
  [ 35  34  37]
  ...
  [163 171 187]
  [164 173 187]
  [164 173 187]]

 [[ 35  34  37]
  [ 34  33  35]
  [ 34  33  35]
  ...
  [164 171 190]
  [166 171 189]
  [166 171 189]]

 [[ 34  33  35]
  [ 34  33  35]
  [ 34  33  35]
  ...
  [164 171 190]
  [166 171 189]
  [165 170 187]]]


[[[ 39  57  72]
  [ 39  57  72]
  [ 40  58  73]
  ...
  [138 170 199]
  [140 169 199]
  [142 170 200]]

 [[ 38  56  71]
  [ 35  52  68]
  [ 38  56  71]
  ...
  [138 170 199]
  [140 169 199]
  [142 170 200]]

 [[ 43  61  74]
  [ 40  59  72]
  [ 40  59  72]
  ...
  [136 170 199]
  [138 170 199]
  [140 171 200]]

 ...

 [[ 31  37  40]
  [ 29  35  38]
  [ 31  34  38]
  

[[[ 55  67  78]
  [ 53  65  77]
  [ 52  64  76]
  ...
  [130 170 193]
  [131 171 194]
  [131 171 194]]

 [[ 55  67  78]
  [ 53  65  77]
  [ 53  65  77]
  ...
  [129 169 192]
  [129 169 192]
  [129 169 192]]

 [[ 55  64  79]
  [ 55  64  79]
  [ 54  63  78]
  ...
  [130 167 191]
  [126 167 190]
  [126 167 190]]

 ...

 [[ 35  37  39]
  [ 34  36  38]
  [ 32  33  35]
  ...
  [157 171 189]
  [155 170 188]
  [155 170 188]]

 [[ 37  36  39]
  [ 36  35  38]
  [ 35  34  37]
  ...
  [158 172 190]
  [159 171 187]
  [157 170 186]]

 [[ 37  36  39]
  [ 36  35  38]
  [ 36  35  38]
  ...
  [158 172 190]
  [159 171 187]
  [157 170 186]]]


[[[ 51  64  80]
  [ 53  65  81]
  [ 54  67  83]
  ...
  [136 168 195]
  [139 169 196]
  [139 169 196]]

 [[ 51  64  80]
  [ 53  65  81]
  [ 54  67  83]
  ...
  [136 168 195]
  [138 168 195]
  [139 169 196]]

 [[ 48  63  79]
  [ 51  66  81]
  [ 52  67  83]
  ...
  [136 168 195]
  [136 168 195]
  [136 168 195]]

 ...

 [[ 36  36  36]
  [ 37  37  37]
  [ 36  36  36]
  

[[[ 64  65  83]
  [ 64  65  83]
  [ 61  64  81]
  ...
  [131 172 193]
  [133 172 193]
  [133 172 193]]

 [[ 64  65  83]
  [ 65  66  84]
  [ 62  65  83]
  ...
  [130 171 192]
  [132 170 192]
  [132 170 192]]

 [[ 63  64  80]
  [ 63  64  80]
  [ 63  64  80]
  ...
  [132 171 190]
  [132 171 190]
  [132 171 190]]

 ...

 [[ 36  36  43]
  [ 36  36  43]
  [ 35  35  42]
  ...
  [158 173 189]
  [157 172 187]
  [155 171 186]]

 [[ 36  37  42]
  [ 36  37  42]
  [ 35  36  40]
  ...
  [159 174 190]
  [160 172 189]
  [159 171 187]]

 [[ 36  37  42]
  [ 36  37  42]
  [ 36  37  42]
  ...
  [159 174 190]
  [160 172 189]
  [159 171 187]]]


[[[ 51  64  80]
  [ 53  65  81]
  [ 54  67  83]
  ...
  [143 175 202]
  [145 175 202]
  [145 175 202]]

 [[ 51  64  80]
  [ 54  67  83]
  [ 54  67  83]
  ...
  [141 173 199]
  [143 172 199]
  [143 172 199]]

 [[ 51  64  80]
  [ 51  64  80]
  [ 53  66  80]
  ...
  [141 173 199]
  [140 172 198]
  [140 172 198]]

 ...

 [[ 38  33  34]
  [ 40  35  36]
  [ 41  36  37]
  

[[[ 61  65  76]
  [ 63  66  77]
  [ 65  68  79]
  ...
  [141 174 198]
  [141 174 198]
  [140 172 197]]

 [[ 61  65  76]
  [ 63  66  77]
  [ 64  67  78]
  ...
  [140 172 197]
  [138 171 195]
  [137 170 194]]

 [[ 56  64  74]
  [ 57  65  76]
  [ 60  68  78]
  ...
  [140 171 195]
  [137 170 194]
  [136 169 193]]

 ...

 [[ 41  32  38]
  [ 41  32  38]
  [ 41  32  38]
  ...
  [159 169 188]
  [161 169 186]
  [161 169 186]]

 [[ 43  33  37]
  [ 43  33  37]
  [ 42  31  35]
  ...
  [163 171 187]
  [163 171 186]
  [163 171 186]]

 [[ 43  33  37]
  [ 43  33  37]
  [ 43  33  37]
  ...
  [163 171 187]
  [164 173 187]
  [164 173 187]]]


[[[ 48  60  70]
  [ 48  60  70]
  [ 49  61  72]
  ...
  [139 177 200]
  [139 177 200]
  [139 177 200]]

 [[ 48  60  70]
  [ 48  60  70]
  [ 50  62  74]
  ...
  [138 175 199]
  [139 177 200]
  [139 177 200]]

 [[ 44  59  70]
  [ 46  60  71]
  [ 46  63  74]
  ...
  [140 174 201]
  [142 174 201]
  [143 175 202]]

 ...

 [[ 35  32  33]
  [ 35  32  33]
  [ 33  31  31]
  

[[[ 53  64  72]
  [ 54  65  73]
  [ 55  66  76]
  ...
  [138 174 202]
  [137 173 201]
  [136 172 200]]

 [[ 53  64  72]
  [ 54  65  73]
  [ 55  66  76]
  ...
  [138 174 202]
  [137 173 201]
  [136 172 200]]

 [[ 51  64  73]
  [ 52  65  74]
  [ 53  66  76]
  ...
  [135 173 201]
  [133 172 200]
  [132 171 199]]

 ...

 [[ 35  33  40]
  [ 34  31  39]
  [ 33  30  37]
  ...
  [154 168 188]
  [153 167 186]
  [153 167 186]]

 [[ 36  34  41]
  [ 34  31  39]
  [ 33  30  37]
  ...
  [154 169 187]
  [155 167 186]
  [155 167 186]]

 [[ 35  33  40]
  [ 33  30  37]
  [ 31  29  36]
  ...
  [155 170 188]
  [157 169 188]
  [157 169 188]]]


[[[ 43  65  75]
  [ 42  63  74]
  [ 45  64  75]
  ...
  [139 174 198]
  [138 172 198]
  [136 171 197]]

 [[ 42  63  74]
  [ 42  63  74]
  [ 46  65  76]
  ...
  [138 173 197]
  [138 172 198]
  [136 171 197]]

 [[ 45  63  76]
  [ 46  65  78]
  [ 47  66  79]
  ...
  [136 171 197]
  [138 170 197]
  [138 170 197]]

 ...

 [[ 37  36  40]
  [ 37  36  40]
  [ 37  36  40]
  

[[[ 73  72  95]
  [ 73  72  95]
  [ 74  74  95]
  ...
  [145 201 231]
  [146 203 232]
  [148 204 233]]

 [[ 73  72  95]
  [ 73  72  95]
  [ 74  74  95]
  ...
  [145 201 231]
  [146 203 232]
  [148 204 233]]

 [[ 73  72  95]
  [ 74  73  96]
  [ 72  74  96]
  ...
  [143 203 229]
  [144 204 230]
  [146 205 232]]

 ...

 [[ 47  48  52]
  [ 46  47  51]
  [ 43  44  49]
  ...
  [175 200 214]
  [175 201 213]
  [175 201 213]]

 [[ 46  47  49]
  [ 46  47  49]
  [ 45  46  48]
  ...
  [177 200 213]
  [177 201 211]
  [177 201 211]]

 [[ 46  47  49]
  [ 46  47  49]
  [ 45  46  48]
  ...
  [178 202 214]
  [178 202 212]
  [177 201 211]]]


[[[ 62  71  99]
  [ 62  71  99]
  [ 61  72 100]
  ...
  [165 204 230]
  [164 203 228]
  [164 203 228]]

 [[ 62  71  99]
  [ 61  69  98]
  [ 60  71  99]
  ...
  [164 203 228]
  [164 203 228]
  [164 203 228]]

 [[ 64  71  97]
  [ 64  71  97]
  [ 63  73  98]
  ...
  [164 204 227]
  [164 204 227]
  [163 203 226]]

 ...

 [[ 48  42  47]
  [ 47  41  46]
  [ 49  40  46]
  

[[[ 64  76  95]
  [ 63  75  94]
  [ 61  75  95]
  ...
  [153 207 228]
  [150 207 227]
  [147 204 225]]

 [[ 64  76  95]
  [ 64  76  95]
  [ 61  75  95]
  ...
  [152 206 227]
  [148 205 226]
  [146 203 223]]

 [[ 60  76  96]
  [ 60  76  96]
  [ 57  75  95]
  ...
  [146 206 226]
  [145 205 225]
  [144 203 223]]

 ...

 [[ 40  36  43]
  [ 42  37  44]
  [ 44  36  44]
  ...
  [180 202 224]
  [184 205 224]
  [187 207 227]]

 [[ 41  34  42]
  [ 42  35  43]
  [ 42  35  43]
  ...
  [180 202 224]
  [184 205 224]
  [187 207 227]]

 [[ 44  36  44]
  [ 44  36  44]
  [ 44  36  44]
  ...
  [181 203 225]
  [184 205 224]
  [185 206 226]]]


[[[ 62  83 102]
  [ 62  83 102]
  [ 62  83 102]
  ...
  [166 208 233]
  [165 207 232]
  [164 206 231]]

 [[ 60  80 100]
  [ 60  80 100]
  [ 60  80 100]
  ...
  [166 208 233]
  [165 207 232]
  [164 206 231]]

 [[ 58  77  96]
  [ 59  78  97]
  [ 59  78  97]
  ...
  [165 206 234]
  [167 206 232]
  [166 205 231]]

 ...

 [[ 38  32  44]
  [ 38  32  44]
  [ 38  32  44]
  

[[[ 62  77  95]
  [ 65  79  97]
  [ 67  81  99]
  ...
  [157 208 225]
  [155 209 225]
  [154 207 224]]

 [[ 62  77  95]
  [ 63  78  96]
  [ 65  79  97]
  ...
  [156 207 224]
  [153 206 223]
  [153 206 223]]

 [[ 62  77  95]
  [ 63  78  96]
  [ 63  78  96]
  ...
  [155 205 224]
  [155 205 224]
  [153 204 223]]

 ...

 [[ 48  45  53]
  [ 49  46  54]
  [ 48  48  55]
  ...
  [178 199 223]
  [180 200 221]
  [181 201 223]]

 [[ 48  45  53]
  [ 49  46  54]
  [ 49  46  54]
  ...
  [183 201 221]
  [183 202 219]
  [183 202 219]]

 [[ 47  44  51]
  [ 48  45  53]
  [ 48  45  53]
  ...
  [184 202 222]
  [184 203 220]
  [183 202 219]]]


[[[ 73  77  99]
  [ 74  78 100]
  [ 74  78 100]
  ...
  [163 201 229]
  [161 200 228]
  [160 199 227]]

 [[ 70  74  96]
  [ 71  75  97]
  [ 73  77  99]
  ...
  [161 200 228]
  [160 199 227]
  [160 199 227]]

 [[ 67  74  94]
  [ 67  74  94]
  [ 68  75  95]
  ...
  [159 200 228]
  [158 200 225]
  [158 200 225]]

 ...

 [[ 33  40  46]
  [ 34  41  47]
  [ 36  41  47]
  

[[[ 45  77  88]
  [ 42  75  86]
  [ 41  74  85]
  ...
  [151 206 231]
  [150 204 232]
  [150 204 232]]

 [[ 45  77  88]
  [ 42  75  86]
  [ 40  73  83]
  ...
  [151 206 231]
  [151 205 233]
  [150 204 232]]

 [[ 48  77  91]
  [ 44  74  87]
  [ 43  73  86]
  ...
  [151 206 231]
  [151 206 231]
  [150 205 230]]

 ...

 [[ 45  39  49]
  [ 46  41  51]
  [ 47  42  52]
  ...
  [179 202 221]
  [181 202 221]
  [181 202 221]]

 [[ 45  39  49]
  [ 46  41  51]
  [ 47  42  52]
  ...
  [181 202 221]
  [183 202 219]
  [182 201 218]]

 [[ 45  39  49]
  [ 46  41  51]
  [ 46  41  51]
  ...
  [181 202 221]
  [183 202 219]
  [182 201 218]]]


[[[ 56  73  88]
  [ 57  74  90]
  [ 59  76  94]
  ...
  [155 199 231]
  [153 196 230]
  [152 195 229]]

 [[ 58  75  91]
  [ 58  75  91]
  [ 58  75  92]
  ...
  [155 199 231]
  [155 199 233]
  [154 197 231]]

 [[ 59  76  94]
  [ 58  75  92]
  [ 58  75  92]
  ...
  [155 202 230]
  [155 202 230]
  [153 201 229]]

 ...

 [[ 44  38  48]
  [ 43  37  47]
  [ 42  36  46]
  

[[[ 55  75  97]
  [ 55  75  97]
  [ 55  75  97]
  ...
  [146 201 228]
  [147 199 227]
  [147 199 227]]

 [[ 56  76  98]
  [ 55  75  97]
  [ 54  74  96]
  ...
  [146 201 228]
  [147 199 227]
  [147 199 227]]

 [[ 57  78  97]
  [ 56  77  96]
  [ 53  76  95]
  ...
  [146 201 228]
  [145 199 227]
  [144 198 226]]

 ...

 [[ 43  40  42]
  [ 44  41  44]
  [ 46  43  46]
  ...
  [185 202 219]
  [185 202 218]
  [184 201 217]]

 [[ 45  39  42]
  [ 45  39  42]
  [ 47  42  45]
  ...
  [186 204 219]
  [188 203 219]
  [187 202 218]]

 [[ 44  38  41]
  [ 45  39  42]
  [ 46  40  44]
  ...
  [187 205 220]
  [189 204 220]
  [189 204 220]]]


[[[ 63  81  89]
  [ 63  81  89]
  [ 63  81  89]
  ...
  [160 204 228]
  [161 206 228]
  [161 206 228]]

 [[ 63  81  89]
  [ 62  80  88]
  [ 62  80  88]
  ...
  [159 203 227]
  [159 203 226]
  [159 203 226]]

 [[ 62  80  88]
  [ 61  79  87]
  [ 58  78  86]
  ...
  [161 203 226]
  [161 203 226]
  [161 203 226]]

 ...

 [[ 34  40  48]
  [ 34  40  48]
  [ 38  42  51]
  

[[[ 59  71  96]
  [ 58  69  95]
  [ 58  69  95]
  ...
  [158 203 232]
  [158 203 232]
  [158 203 232]]

 [[ 58  69  95]
  [ 55  67  93]
  [ 54  66  91]
  ...
  [157 201 230]
  [157 201 230]
  [157 201 230]]

 [[ 60  70  93]
  [ 57  68  91]
  [ 55  65  89]
  ...
  [151 200 231]
  [150 199 230]
  [149 198 229]]

 ...

 [[ 31  37  40]
  [ 31  37  40]
  [ 34  39  43]
  ...
  [173 205 218]
  [175 205 216]
  [174 204 215]]

 [[ 27  35  38]
  [ 27  35  38]
  [ 28  35  41]
  ...
  [173 206 216]
  [174 205 213]
  [174 205 213]]

 [[ 26  34  37]
  [ 27  35  38]
  [ 28  35  41]
  ...
  [172 204 215]
  [174 205 213]
  [174 205 213]]]


[[[ 63  71  93]
  [ 63  71  93]
  [ 64  73  94]
  ...
  [157 208 232]
  [154 208 231]
  [153 206 230]]

 [[ 64  73  94]
  [ 64  73  94]
  [ 65  74  95]
  ...
  [157 208 232]
  [154 208 231]
  [153 206 230]]

 [[ 67  73  95]
  [ 67  73  95]
  [ 67  73  95]
  ...
  [157 208 234]
  [154 207 232]
  [152 204 230]]

 ...

 [[ 42  42  49]
  [ 41  41  48]
  [ 40  40  47]
  

[[[ 51  78  92]
  [ 52  79  93]
  [ 53  80  94]
  ...
  [164 204 234]
  [164 204 234]
  [165 205 235]]

 [[ 50  77  91]
  [ 51  78  92]
  [ 52  79  93]
  ...
  [163 203 233]
  [163 203 233]
  [163 203 233]]

 [[ 52  77  91]
  [ 52  77  91]
  [ 53  78  92]
  ...
  [162 203 230]
  [162 202 232]
  [162 202 232]]

 ...

 [[ 40  42  44]
  [ 40  42  44]
  [ 41  43  45]
  ...
  [180 199 219]
  [184 200 218]
  [184 200 218]]

 [[ 41  43  45]
  [ 41  43  45]
  [ 42  44  46]
  ...
  [184 200 218]
  [185 202 219]
  [185 202 219]]

 [[ 43  45  47]
  [ 43  45  47]
  [ 43  45  47]
  ...
  [186 203 220]
  [186 203 220]
  [185 202 219]]]


[[[ 44  77  92]
  [ 45  79  94]
  [ 46  80  95]
  ...
  [149 205 223]
  [150 206 224]
  [152 207 225]]

 [[ 44  77  92]
  [ 45  79  94]
  [ 46  80  95]
  ...
  [149 205 223]
  [150 206 224]
  [150 206 224]]

 [[ 49  77  95]
  [ 50  78  96]
  [ 51  79  97]
  ...
  [151 203 225]
  [153 205 224]
  [153 205 224]]

 ...

 [[ 45  38  44]
  [ 45  38  44]
  [ 46  40  44]
  

[[[ 63  77 102]
  [ 63  77 102]
  [ 63  77 102]
  ...
  [149 202 228]
  [147 203 228]
  [147 203 228]]

 [[ 60  75 100]
  [ 61  76 101]
  [ 63  77 102]
  ...
  [149 202 228]
  [146 201 227]
  [146 201 227]]

 [[ 61  73  98]
  [ 62  74 100]
  [ 65  77 100]
  ...
  [148 202 225]
  [148 202 225]
  [147 201 224]]

 ...

 [[ 45  42  45]
  [ 46  43  46]
  [ 49  45  48]
  ...
  [182 206 223]
  [184 207 221]
  [183 205 220]]

 [[ 50  42  46]
  [ 51  43  47]
  [ 55  47  51]
  ...
  [184 205 224]
  [182 203 220]
  [181 202 219]]

 [[ 50  42  46]
  [ 51  43  47]
  [ 54  46  49]
  ...
  [182 203 222]
  [181 202 219]
  [180 201 218]]]


[[[ 56  78 102]
  [ 56  78 102]
  [ 56  78 102]
  ...
  [159 203 227]
  [161 202 227]
  [161 202 227]]

 [[ 55  77 101]
  [ 56  78 102]
  [ 56  78 102]
  ...
  [159 203 227]
  [161 202 227]
  [161 202 227]]

 [[ 58  78 102]
  [ 60  79 103]
  [ 60  79 103]
  ...
  [157 203 227]
  [157 203 227]
  [157 203 227]]

 ...

 [[ 48  40  44]
  [ 50  42  46]
  [ 53  45  48]
  

[[[ 60  76  96]
  [ 60  76  96]
  [ 60  76  96]
  ...
  [154 205 228]
  [149 202 228]
  [148 201 227]]

 [[ 60  76  96]
  [ 61  77  97]
  [ 61  77  97]
  ...
  [155 206 230]
  [149 202 228]
  [148 201 227]]

 [[ 61  78  96]
  [ 61  78  96]
  [ 60  76  96]
  ...
  [155 207 228]
  [153 204 227]
  [150 201 225]]

 ...

 [[ 42  38  50]
  [ 42  38  50]
  [ 40  38  50]
  ...
  [176 207 224]
  [179 207 226]
  [179 207 226]]

 [[ 41  37  49]
  [ 42  38  50]
  [ 43  39  51]
  ...
  [181 207 226]
  [181 208 224]
  [180 207 223]]

 [[ 42  38  50]
  [ 43  39  51]
  [ 44  40  52]
  ...
  [181 207 226]
  [181 208 224]
  [181 208 224]]]


[[[ 67  77  96]
  [ 67  77  96]
  [ 67  77  96]
  ...
  [149 201 229]
  [146 200 230]
  [146 200 230]]

 [[ 69  78  97]
  [ 69  78  97]
  [ 67  77  96]
  ...
  [149 201 229]
  [146 200 230]
  [146 200 230]]

 [[ 69  78  97]
  [ 69  78  97]
  [ 65  77  96]
  ...
  [148 204 229]
  [147 202 229]
  [146 201 228]]

 ...

 [[ 39  38  47]
  [ 41  40  49]
  [ 43  43  52]
  

[[[ 51  77  94]
  [ 50  76  92]
  [ 50  76  92]
  ...
  [148 198 233]
  [150 197 233]
  [150 197 233]]

 [[ 50  76  92]
  [ 49  75  91]
  [ 49  75  91]
  ...
  [146 195 231]
  [148 195 231]
  [148 195 231]]

 [[ 52  77  91]
  [ 52  77  91]
  [ 51  75  90]
  ...
  [144 192 227]
  [144 191 229]
  [146 192 230]]

 ...

 [[ 37  34  44]
  [ 37  34  44]
  [ 38  35  45]
  ...
  [181 202 219]
  [181 203 218]
  [178 201 215]]

 [[ 37  34  44]
  [ 37  34  44]
  [ 38  35  45]
  ...
  [184 204 219]
  [183 204 216]
  [182 202 215]]

 [[ 38  35  45]
  [ 38  35  45]
  [ 38  35  45]
  ...
  [185 205 220]
  [184 205 217]
  [183 204 216]]]


[[[ 58  82  98]
  [ 59  83  99]
  [ 60  84 101]
  ...
  [160 203 230]
  [162 203 230]
  [161 201 229]]

 [[ 54  78  95]
  [ 55  79  96]
  [ 55  79  96]
  ...
  [157 201 228]
  [159 200 228]
  [158 199 227]]

 [[ 52  76  92]
  [ 52  76  92]
  [ 52  76  92]
  ...
  [154 196 226]
  [153 195 225]
  [153 195 225]]

 ...

 [[ 53  41  50]
  [ 53  41  50]
  [ 52  40  49]
  

[[[ 53  80  87]
  [ 52  79  86]
  [ 52  78  88]
  ...
  [159 205 231]
  [157 201 230]
  [157 201 230]]

 [[ 53  80  87]
  [ 52  79  86]
  [ 52  78  88]
  ...
  [158 203 230]
  [157 201 230]
  [157 201 230]]

 [[ 55  79  89]
  [ 55  79  89]
  [ 54  78  88]
  ...
  [158 203 232]
  [158 203 232]
  [157 201 230]]

 ...

 [[ 47  43  50]
  [ 47  43  50]
  [ 49  44  51]
  ...
  [183 205 220]
  [182 205 217]
  [182 205 217]]

 [[ 48  40  51]
  [ 48  40  51]
  [ 51  43  51]
  ...
  [182 204 219]
  [182 205 217]
  [182 205 217]]

 [[ 48  40  51]
  [ 49  41  52]
  [ 51  43  51]
  ...
  [181 203 218]
  [181 204 216]
  [182 205 217]]]


[[[ 46  79  89]
  [ 46  79  89]
  [ 49  79  90]
  ...
  [156 206 232]
  [152 204 230]
  [150 203 229]]

 [[ 41  74  85]
  [ 41  74  85]
  [ 45  76  87]
  ...
  [157 208 234]
  [153 206 231]
  [152 204 230]]

 [[ 39  72  82]
  [ 38  70  81]
  [ 42  72  83]
  ...
  [158 206 232]
  [157 205 231]
  [156 204 230]]

 ...

 [[ 50  38  47]
  [ 50  38  47]
  [ 50  38  47]
  

[[[ 52  79  95]
  [ 53  80  96]
  [ 53  80  94]
  ...
  [164 201 232]
  [166 201 232]
  [166 201 232]]

 [[ 53  80  96]
  [ 54  81  97]
  [ 54  82  95]
  ...
  [163 200 230]
  [165 200 230]
  [165 200 230]]

 [[ 55  79  96]
  [ 56  80  97]
  [ 56  80  97]
  ...
  [161 201 230]
  [161 201 230]
  [161 201 230]]

 ...

 [[ 43  44  42]
  [ 43  44  42]
  [ 44  45  43]
  ...
  [176 200 217]
  [178 201 215]
  [178 201 215]]

 [[ 43  44  42]
  [ 42  43  40]
  [ 42  43  40]
  ...
  [180 201 218]
  [178 201 215]
  [178 201 215]]

 [[ 43  44  42]
  [ 40  40  38]
  [ 38  39  37]
  ...
  [178 200 217]
  [180 202 217]
  [180 202 217]]]


[[[ 50  76  92]
  [ 51  77  94]
  [ 51  77  94]
  ...
  [157 203 234]
  [157 203 234]
  [156 202 233]]

 [[ 51  77  94]
  [ 51  77  94]
  [ 51  77  94]
  ...
  [156 202 233]
  [155 201 232]
  [155 201 232]]

 [[ 51  77  94]
  [ 52  79  95]
  [ 51  77  94]
  ...
  [151 201 229]
  [151 201 229]
  [151 201 229]]

 ...

 [[ 42  42  42]
  [ 42  42  42]
  [ 42  41  44]
  

[[[ 51  73  90]
  [ 51  73  90]
  [ 53  74  91]
  ...
  [150 204 232]
  [152 204 232]
  [152 204 232]]

 [[ 54  75  92]
  [ 54  75  92]
  [ 55  77  94]
  ...
  [150 204 232]
  [150 203 230]
  [150 203 230]]

 [[ 59  77  92]
  [ 60  78  93]
  [ 60  78  93]
  ...
  [149 201 229]
  [149 201 229]
  [149 201 229]]

 ...

 [[ 45  38  44]
  [ 46  40  45]
  [ 47  41  46]
  ...
  [181 203 225]
  [181 204 223]
  [180 203 222]]

 [[ 49  41  45]
  [ 49  41  45]
  [ 50  42  46]
  ...
  [180 202 224]
  [182 202 224]
  [182 202 224]]

 [[ 51  43  47]
  [ 51  43  47]
  [ 53  45  48]
  ...
  [179 201 223]
  [181 201 223]
  [181 201 223]]]


[[[ 51  72  92]
  [ 53  73  93]
  [ 57  75  95]
  ...
  [154 201 225]
  [153 199 224]
  [153 199 224]]

 [[ 53  73  93]
  [ 54  75  94]
  [ 57  75  95]
  ...
  [153 199 224]
  [152 198 223]
  [153 199 224]]

 [[ 55  74  91]
  [ 57  76  94]
  [ 58  77  95]
  ...
  [150 199 223]
  [153 199 224]
  [154 201 225]]

 ...

 [[ 58  40  52]
  [ 56  39  51]
  [ 55  38  49]
  

[[[ 53  74  91]
  [ 54  75  92]
  [ 55  77  94]
  ...
  [147 195 228]
  [146 194 227]
  [146 194 227]]

 [[ 54  75  92]
  [ 54  75  92]
  [ 55  77  94]
  ...
  [146 194 227]
  [144 192 226]
  [146 194 227]]

 [[ 56  75  92]
  [ 56  75  92]
  [ 59  76  94]
  ...
  [143 196 223]
  [142 194 224]
  [143 195 225]]

 ...

 [[ 53  42  42]
  [ 51  40  39]
  [ 49  37  37]
  ...
  [185 203 225]
  [184 201 224]
  [184 201 224]]

 [[ 54  44  41]
  [ 52  42  39]
  [ 49  38  35]
  ...
  [183 203 225]
  [184 201 224]
  [184 201 224]]

 [[ 54  44  41]
  [ 52  42  39]
  [ 50  39  36]
  ...
  [183 203 225]
  [184 201 224]
  [184 201 224]]]


[[[ 64  77  93]
  [ 64  77  93]
  [ 63  76  92]
  ...
  [143 202 231]
  [141 202 231]
  [141 202 231]]

 [[ 65  78  94]
  [ 65  78  94]
  [ 64  77  93]
  ...
  [144 203 232]
  [141 202 231]
  [141 202 231]]

 [[ 69  78  97]
  [ 69  78  97]
  [ 67  79  97]
  ...
  [144 203 232]
  [141 202 231]
  [141 202 231]]

 ...

 [[ 42  38  41]
  [ 42  38  41]
  [ 43  40  42]
  

[[[ 58  75  84]
  [ 58  75  84]
  [ 60  78  86]
  ...
  [157 202 229]
  [153 201 229]
  [152 199 228]]

 [[ 56  74  83]
  [ 58  75  84]
  [ 59  76  85]
  ...
  [157 202 229]
  [153 201 229]
  [152 199 228]]

 [[ 53  73  81]
  [ 54  74  83]
  [ 57  77  85]
  ...
  [153 201 228]
  [150 201 227]
  [150 201 227]]

 ...

 [[ 38  39  41]
  [ 40  42  44]
  [ 41  43  45]
  ...
  [185 207 228]
  [182 205 224]
  [181 204 223]]

 [[ 41  40  42]
  [ 42  41  44]
  [ 43  42  45]
  ...
  [185 206 226]
  [184 205 224]
  [183 204 223]]

 [[ 42  41  44]
  [ 42  41  44]
  [ 43  42  45]
  ...
  [184 205 224]
  [184 205 224]
  [183 204 223]]]


[[[ 67  74  94]
  [ 68  75  95]
  [ 66  77  93]
  ...
  [162 203 230]
  [162 203 230]
  [163 204 231]]

 [[ 64  71  90]
  [ 65  72  91]
  [ 65  75  92]
  ...
  [161 201 229]
  [162 203 230]
  [162 203 230]]

 [[ 59  69  88]
  [ 62  71  90]
  [ 64  73  92]
  ...
  [159 202 229]
  [161 201 230]
  [161 201 230]]

 ...

 [[ 42  45  44]
  [ 43  46  45]
  [ 43  45  47]
  

In [ ]:
#detections = detect_fn(input_tensor)